### PR TITLE
[Bugfix] Fix testing error in ControllerTestBase with alignment with backend interface

### PR DESCRIPTION
**Pull request by hdygxsj**
### Purpose

Fixed errors in api testing #103 

Aligned API testing with backend interface.

Unit tests changed to use H2 database.

### CODE REVIEW

**Review by s7monk — APPROVED** [review]
LGTM

**Comment by SteNicholas** [comment]
@hdygxsj, what's the bug in the api test? Could you create new issue to describe the bug detail?

**Comment by hdygxsj** [comment]
> @hdygxsj, what's the bug in the api test? Could you create new issue to describe the bug detail?

#103

**Review by SteNicholas — APPROVED** [review]
LGTM. Thanks for @hdygxsj contribution.

**Pull request merged**
