### PR TITLE
[Feature] Introduce history interface

### PR DESCRIPTION
**Pull request by s7monk**
close: https://github.com/apache/paimon-webui/issues/252

### Purpose

Introduce history interface to select history.

### Tests

HistoryControllerTest

### API and Format

```
@RestController
@RequestMapping("/api/history")
public class HistoryController {

    @Autowired private HistoryService historyService;

    @SaCheckPermission("playground:history:query")
    @GetMapping("/{id}")
    public R<History> getStatement(@PathVariable("id") Integer id) {
        return R.succeed(historyService.getById(id));
    }

    @SaCheckPermission("playground:history:list")
    @GetMapping("/list")
    public PageR<History> listSelectHistories(History selectHistory) {
        IPage<History> page = PageSupport.startPage();
        List<History> selectHistories = historyService.listHistories(page, selectHistory);
        return PageR.<History>builder()
                .success(true)
                .total(page.getTotal())
                .data(selectHistories)
                .build();
    }

    @SaCheckPermission("playground:history:query")
    @GetMapping("/all")
    public R<List<History>> all() {
        return R.succeed(historyService.list());
    }
}
```

### CODE REVIEW

**Comment by SteNicholas** [comment]
@s7monk, why not introduce history interface?

**Comment by s7monk** [comment]
> Purpose

This is the history interface. Maybe my purpose description is wrong.

**Comment by SteNicholas** [comment]
@s7monk, the controller should be `HistoryController` instead of `SelectHistoryController`.

**Comment by s7monk** [comment]
> @s7monk, the controller should be `HistoryController` instead of `SelectHistoryController`.

done.

**Review by SteNicholas — APPROVED** [review]
LGTM.

**Pull request merged**
